FROM quay.io/keycloak/keycloak:26.3.3
COPY providers/keycloak-pwned-policy.jar /opt/keycloak/providers/keycloak-pwned-policy.jar
COPY themes /opt/keycloak/themes
RUN /opt/keycloak/bin/kc.sh build
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev"]